#!/bin/bash

# Write crontab file
echo "${UPLOAD_INTERVAL} acdcli upload -o /mnt/local-encrypted/* ${ACD_ROOT}" > /etc/cron.d/uploads
echo "${UPLOAD_INTERVAL} find /mnt/local-decrypted/* -ctime +${LOCAL_DAYS} -exec rm -f {} \;" >> /etc/cron.d/uploads

# Load cron and switch process
crontab /etc/cron.d/uploads
exec cron -f
